#!/usr/bin/env bash
# Launches notion

if [[ ! -e "/opt/notion" ]]; then
  echo "Error: /opt/notion not found"
  exit 1
fi

pushd "/opt/notion" >/dev/null || exit 1
./electron app.asar
popd >/dev/null || exit 1
